package br.gov.mec.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solicitante implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Nome")
   private java.lang.String nome;
   @org.kie.api.definition.type.Label("CNPJ")
   private java.lang.String cnpj;

   @org.kie.api.definition.type.Label(value = "Email")
   private java.lang.String email;

   public Solicitante()
   {
   }

   public java.lang.String getNome()
   {
      return this.nome;
   }

   public void setNome(java.lang.String nome)
   {
      this.nome = nome;
   }

   public java.lang.String getCnpj()
   {
      return this.cnpj;
   }

   public void setCnpj(java.lang.String cnpj)
   {
      this.cnpj = cnpj;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public Solicitante(java.lang.String nome, java.lang.String cnpj,
         java.lang.String email)
   {
      this.nome = nome;
      this.cnpj = cnpj;
      this.email = email;
   }

}